In [6]:
import pandas as pd
from pathlib import Path
datos = pd.read_csv("insurance_claims.csv")
datos.head(10)
DatosLimpios=datos.copy()
DatosLimpios= DatosLimpios.drop("_c39", axis=1)
datos.head(10)
#print(f"Total columnas: {DatosLimpios.shape[1]}")
#list(datos.columns)

#DatosLimpios.head(500)

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN
5,256,39,104594,2006-10-12,OH,250/500,1000,1351.10,0,478456,...,NO,64100,6410,6410,51280,Saab,95,2003,Y,NaN
6,137,34,413978,2000-06-04,IN,250/500,1000,1333.35,0,441716,...,?,78650,21450,7150,50050,Nissan,Pathfinder,2012,N,NaN
7,165,37,429027,1990-02-03,IL,100/300,1000,1137.03,0,603195,...,YES,51590,9380,9380,32830,Audi,A5,2015,N,NaN
8,27,33,485665,1997-02-05,IL,100/300,500,1442.99,0,601734,...,YES,27700,2770,2770,22160,Toyota,Camry,2012,N,NaN
9,212,42,636550,2011-07-25,IL,100/300,500,1315.68,0,600983,...,?,42300,4700,4700,32900,Saab,92x,1996,N,NaN

In [7]:
# Montos de reclamo más altos (total)
print("Máximo total_claim_amount:", datos["total_claim_amount"].max())

datos.sort_values("total_claim_amount", ascending=False)[
    ["total_claim_amount", "injury_claim", "property_claim", "vehicle_claim"]
].head(30)

Máximo total_claim_amount: 114920

     total_claim_amount  injury_claim  property_claim  vehicle_claim
11               114920         17680           17680          79560
149              112320         17280           17280          77760
996              108480         18080           18080          72320
565              108030         16620           16620          74790
163              107900         10790           21580          75530
718              105820         16280           16280          73260
733              105040         16160           16160          72720
479              104610         19020           19020          66570
458              103560          8630           17260          77670
189              101860         18520           18520          64820
293              101010         15540           15540          69930
181              100800         16800           16800          67200
384              100210         18220           18220          63770
164               99990         18180           18180          63630
145               99320          7640           15280          76400
247               98670         15180           15180          68310
91                98340          8940           17880          71520
974               98280         15120            7560          75600
23                98160          8180           16360          73620
907               97080         16180           16180          64720
41                97080         16180           16180          64720
687               95900         13700           20550          61650
419               95810         14740           14740          66330
455               95150         17300           17300          60550
655               95000          9500            9500          76000
850               94930          8630            8630          77670
413               94560          7880           15760          70920
290               94160          8560           17120          68480
301               93730         14420           21630          57680
94                93720         17040            8520          68160

In [8]:
# Percentiles de los montos totales reclamados
percentiles = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
datos["total_claim_amount"].quantile(percentiles)

0.05      4320.0
0.10      5756.0
0.25     41812.5
0.50     58055.0
0.75     70592.5
0.90     81364.0
0.95     88413.0
0.99    101018.5
Name: total_claim_amount, dtype: float64

In [9]:
# Contar NaN en una columna específica
# Reemplaza 'nombre_columna' por la columna que quieras
import pandas as pd
from pathlib import Path
datos = pd.read_csv("insurance_claims.csv")
col = "_c39"
print(f"NaN en {col}:", datos[col].isna().sum())

NaN en _c39: 1000

In [36]:
corr = datos.corr(numeric_only=True)

threshold = 0.9
corr_pairs = (
    corr.where(~corr.eq(1.0))  # quitar diagonal
        .stack()
        .sort_values(ascending=False)
)
print("Correlaciones directas fuertes:")
print(corr_pairs[corr_pairs >= threshold].head(10))

Correlaciones directas fuertes:
vehicle_claim       total_claim_amount    0.982773
total_claim_amount  vehicle_claim         0.982773
age                 months_as_customer    0.922098
months_as_customer  age                   0.922098
dtype: float64

In [37]:
# Ver filas duplicadas
duplicadas = datos[datos.duplicated()]
print(f"Filas duplicadas: {len(duplicadas)}")
duplicadas

Filas duplicadas: 0

Empty DataFrame
Columns: [months_as_customer, age, policy_number, policy_bind_date, policy_state, policy_csl, policy_deductable, policy_annual_premium, umbrella_limit, insured_zip, insured_sex, insured_education_level, insured_occupation, insured_hobbies, insured_relationship, capital-gains, capital-loss, incident_date, incident_type, collision_type, incident_severity, authorities_contacted, incident_state, incident_city, incident_location, incident_hour_of_the_day, number_of_vehicles_involved, property_damage, bodily_injuries, witnesses, police_report_available, total_claim_amount, injury_claim, property_claim, vehicle_claim, auto_make, auto_model, auto_year, fraud_reported, _c39]
Index: []

In [10]:

cols = ["policy_number", "insured_zip"]
repetidas = datos[datos.duplicated(subset=cols, keep=False)]
print(f"Filas con información repetida en {cols}: {len(repetidas)}")
repetidas.sort_values(cols)
datos.head(1)

Filas con información repetida en ['policy_number', 'insured_zip']: 0

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN

In [11]:
nan_counts = datos.isna().sum()
nan_counts[nan_counts > 0]

authorities_contacted      91
_c39                     1000
dtype: int64

In [59]:
datos.head(10)

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,insured_sex,insured_education_level,insured_occupation,insured_hobbies,insured_relationship,capital-gains,capital-loss,incident_date,incident_type,collision_type,incident_severity,authorities_contacted,incident_state,incident_city,incident_location,incident_hour_of_the_day,number_of_vehicles_involved,property_damage,bodily_injuries,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,MALE,MD,craft-repair,sleeping,husband,53300,0,2015-01-25,Single Vehicle Collision,Side Collision,Major Damage,Police,SC,Columbus,9935 4th Drive,5,1,YES,1,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,MALE,MD,machine-op-inspct,reading,other-relative,0,0,2015-01-21,Vehicle Theft,?,Minor Damage,Police,VA,Riverwood,6608 MLK Hwy,8,1,?,0,0,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,FEMALE,PhD,sales,board-games,own-child,35100,0,2015-02-22,Multi-vehicle Collision,Rear Collision,Minor Damage,Police,NY,Columbus,7121 Francis Lane,7,3,NO,2,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,FEMALE,PhD,armed-forces,board-games,unmarried,48900,-62400,2015-01-10,Single Vehicle Collision,Front Collision,Major Damage,Police,OH,Arlington,6956 Maple Drive,5,1,?,1,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,MALE,Associate,sales,board-games,unmarried,66000,-46000,2015-02-17,Vehicle Theft,?,Minor Damage,NaN,NY,Arlington,3041 3rd Ave,20,1,NO,0,1,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN
5,256,39,104594,2006-10-12,OH,250/500,1000,1351.10,0,478456,FEMALE,PhD,tech-support,bungie-jumping,unmarried,0,0,2015-01-02,Multi-vehicle Collision,Rear Collision,Major Damage,Fire,SC,Arlington,8973 Washington St,19,3,NO,0,2,NO,64100,6410,6410,51280,Saab,95,2003,Y,NaN
6,137,34,413978,2000-06-04,IN,250/500,1000,1333.35,0,441716,MALE,PhD,prof-specialty,board-games,husband,0,-77000,2015-01-13,Multi-vehicle Collision,Front Collision,Minor Damage,Police,NY,Springfield,5846 Weaver Drive,0,3,?,0,0,?,78650,21450,7150,50050,Nissan,Pathfinder,2012,N,NaN
7,165,37,429027,1990-02-03,IL,100/300,1000,1137.03,0,603195,MALE,Associate,tech-support,base-jumping,unmarried,0,0,2015-02-27,Multi-vehicle Collision,Front Collision,Total Loss,Police,VA,Columbus,3525 3rd Hwy,23,3,?,2,2,YES,51590,9380,9380,32830,Audi,A5,2015,N,NaN
8,27,33,485665,1997-02-05,IL,100/300,500,1442.99,0,601734,FEMALE,PhD,other-service,golf,own-child,0,0,2015-01-30,Single Vehicle Collision,Front Collision,Total Loss,Police,WV,Arlington,4872 Rock Ridge,21,1,NO,1,1,YES,27700,2770,2770,22160,Toyota,Camry,2012,N,NaN
9,212,42,636550,2011-07-25,IL,100/300,500,1315.68,0,600983,MALE,PhD,priv-house-serv,camping,wife,0,-39300,2015-01-05,Single Vehicle Collision,Rear Collision,Total Loss,Other,NC,Hillsdale,3066 Francis Ave,14,1,NO,2,1,?,42300,4700,4700,32900,Saab,92x,1996,N,NaN

In [12]:
datos.loc[datos["collision_type"] == "?", ["incident_type", "collision_type"]]

     incident_type collision_type
1    Vehicle Theft              ?
4    Vehicle Theft              ?
13      Parked Car              ?
26      Parked Car              ?
27   Vehicle Theft              ?
..             ...            ...
964  Vehicle Theft              ?
969  Vehicle Theft              ?
983     Parked Car              ?
994     Parked Car              ?
999     Parked Car              ?

[178 rows x 2 columns]

In [19]:
datos["incident_date"] = pd.to_datetime(datos["incident_date"]) #Convertir a dataTime
reclamos_por_mes = datos["incident_date"].dt.month.value_counts().sort_index()
reclamos_por_mes.reset_index(name="reclamos")

#mes_max = reclamos_por_mes.idxmax()
#total_max = reclamos_por_mes.max()
#print(reclamos_por_mes.index)
#print(f"reclamos_por_mes: {reclamos_por_mes}")
#print("Mes con mas reclamos:", mes_max  )
#print("Total de reclamos en ese mes:", total_max)

   incident_date  reclamos
0              1       516
1              2       472
2              3        12